package com.example.chatbottextandalsoimage.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF625F4D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB9B4A0)
val onPrimaryContainerLight = Color(0xFF2B291A)
val secondaryLight = Color(0xFF615E56)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEBE6DB)
val onSecondaryContainerLight = Color(0xFF4C4A42)
val tertiaryLight = Color(0xFF596156)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAFB7AA)
val onTertiaryContainerLight = Color(0xFF232B22)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF8F5)
val onBackgroundLight = Color(0xFF1C1B1A)
val surfaceLight = Color(0xFFFDF8F5)
val onSurfaceLight = Color(0xFF1C1B1A)
val surfaceVariantLight = Color(0xFFE7E2D6)
val onSurfaceVariantLight = Color(0xFF49473E)
val outlineLight = Color(0xFF7A776D)
val outlineVariantLight = Color(0xFFCBC6BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31302E)
val inverseOnSurfaceLight = Color(0xFFF4F0ED)
val inversePrimaryLight = Color(0xFFCCC7B2)
val surfaceDimLight = Color(0xFFDDD9D6)
val surfaceBrightLight = Color(0xFFFDF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F0)
val surfaceContainerLight = Color(0xFFF1EDEA)
val surfaceContainerHighLight = Color(0xFFECE7E4)
val surfaceContainerHighestLight = Color(0xFFE6E2DF)

val primaryLightMediumContrast = Color(0xFF464333)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF797563)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF45433B)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF77746C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF3D453B)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6F776B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFDF8F5)
val onBackgroundLightMediumContrast = Color(0xFF1C1B1A)
val surfaceLightMediumContrast = Color(0xFFFDF8F5)
val onSurfaceLightMediumContrast = Color(0xFF1C1B1A)
val surfaceVariantLightMediumContrast = Color(0xFFE7E2D6)
val onSurfaceVariantLightMediumContrast = Color(0xFF45433A)
val outlineLightMediumContrast = Color(0xFF625F56)
val outlineVariantLightMediumContrast = Color(0xFF7E7B71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF31302E)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F0ED)
val inversePrimaryLightMediumContrast = Color(0xFFCCC7B2)
val surfaceDimLightMediumContrast = Color(0xFFDDD9D6)
val surfaceBrightLightMediumContrast = Color(0xFFFDF8F5)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7F3F0)
val surfaceContainerLightMediumContrast = Color(0xFFF1EDEA)
val surfaceContainerHighLightMediumContrast = Color(0xFFECE7E4)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE6E2DF)

val primaryLightHighContrast = Color(0xFF252215)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF464333)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF24221C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF45433B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1D241B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3D453B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFDF8F5)
val onBackgroundLightHighContrast = Color(0xFF1C1B1A)
val surfaceLightHighContrast = Color(0xFFFDF8F5)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7E2D6)
val onSurfaceVariantLightHighContrast = Color(0xFF26241D)
val outlineLightHighContrast = Color(0xFF45433A)
val outlineVariantLightHighContrast = Color(0xFF45433A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF31302E)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF2ECD6)
val surfaceDimLightHighContrast = Color(0xFFDDD9D6)
val surfaceBrightLightHighContrast = Color(0xFFFDF8F5)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7F3F0)
val surfaceContainerLightHighContrast = Color(0xFFF1EDEA)
val surfaceContainerHighLightHighContrast = Color(0xFFECE7E4)
val surfaceContainerHighestLightHighContrast = Color(0xFFE6E2DF)

val primaryDark = Color(0xFFD1CCB7)
val onPrimaryDark = Color(0xFF333122)
val primaryContainerDark = Color(0xFFA8A38F)
val onPrimaryContainerDark = Color(0xFF1A180B)
val secondaryDark = Color(0xFFCBC6BC)
val onSecondaryDark = Color(0xFF323029)
val secondaryContainerDark = Color(0xFF3F3D36)
val onSecondaryContainerDark = Color(0xFFD5D0C6)
val tertiaryDark = Color(0xFFC6CEC0)
val onTertiaryDark = Color(0xFF2B3229)
val tertiaryContainerDark = Color(0xFF9DA598)
val onTertiaryContainerDark = Color(0xFF121911)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141312)
val onBackgroundDark = Color(0xFFE6E2DF)
val surfaceDark = Color(0xFF141312)
val onSurfaceDark = Color(0xFFE6E2DF)
val surfaceVariantDark = Color(0xFF49473E)
val onSurfaceVariantDark = Color(0xFFCBC6BB)
val outlineDark = Color(0xFF949086)
val outlineVariantDark = Color(0xFF49473E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E2DF)
val inverseOnSurfaceDark = Color(0xFF31302E)
val inversePrimaryDark = Color(0xFF625F4D)
val surfaceDimDark = Color(0xFF141312)
val surfaceBrightDark = Color(0xFF3A3937)
val surfaceContainerLowestDark = Color(0xFF0F0E0D)
val surfaceContainerLowDark = Color(0xFF1C1B1A)
val surfaceContainerDark = Color(0xFF201F1E)
val surfaceContainerHighDark = Color(0xFF2B2A28)
val surfaceContainerHighestDark = Color(0xFF363533)

val primaryDarkMediumContrast = Color(0xFFD1CCB7)
val onPrimaryDarkMediumContrast = Color(0xFF1A180B)
val primaryContainerDarkMediumContrast = Color(0xFFA8A38F)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCFCAC0)
val onSecondaryDarkMediumContrast = Color(0xFF181610)
val secondaryContainerDarkMediumContrast = Color(0xFF949087)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC6CEC0)
val onTertiaryDarkMediumContrast = Color(0xFF121910)
val tertiaryContainerDarkMediumContrast = Color(0xFF9DA598)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF141312)
val onBackgroundDarkMediumContrast = Color(0xFFE6E2DF)
val surfaceDarkMediumContrast = Color(0xFF141312)
val onSurfaceDarkMediumContrast = Color(0xFFFEFAF7)
val surfaceVariantDarkMediumContrast = Color(0xFF49473E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCFCABF)
val outlineDarkMediumContrast = Color(0xFFA6A398)
val outlineVariantDarkMediumContrast = Color(0xFF868379)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E2DF)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B2A28)
val inversePrimaryDarkMediumContrast = Color(0xFF4B4838)
val surfaceDimDarkMediumContrast = Color(0xFF141312)
val surfaceBrightDarkMediumContrast = Color(0xFF3A3937)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0E0D)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1B1A)
val surfaceContainerDarkMediumContrast = Color(0xFF201F1E)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2B2A28)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF363533)

val primaryDarkHighContrast = Color(0xFFFFFAF3)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD0CBB6)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF3)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCFCAC0)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF5FDEF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC5CDBF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF141312)
val onBackgroundDarkHighContrast = Color(0xFFE6E2DF)
val surfaceDarkHighContrast = Color(0xFF141312)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF3)
val outlineDarkHighContrast = Color(0xFFCFCABF)
val outlineVariantDarkHighContrast = Color(0xFFCFCABF)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E2DF)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2D2A1C)
val surfaceDimDarkHighContrast = Color(0xFF141312)
val surfaceBrightDarkHighContrast = Color(0xFF3A3937)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0E0D)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C1B1A)
val surfaceContainerDarkHighContrast = Color(0xFF201F1E)
val surfaceContainerHighDarkHighContrast = Color(0xFF2B2A28)
val surfaceContainerHighestDarkHighContrast = Color(0xFF363533)















